const Data = [
  {
    id: 1,
    name: "Laptop",
    price: 50000,
    freeDelivery: true,
    rating: 4.2,
    reviews: 204,
    image: "images/Laptop.jpg",
    qty: 1,
  },
  {
    id: 2,
    name: "iPhone 13",
    price: 72000,
    freeDelivery: false,
    rating: 4.5,
    reviews: 535,
    image: "images/iphone13.jpg",
    qty: 1,
  },
  {
    id: 3,
    name: "Boat Air Buds",
    price: 13000,
    freeDelivery: false,
    rating: 4.9,
    reviews: 156,
    image: "images/boatbuds.jpg",
    qty: 1,
  },
  {
    id: 4,
    name: "Mobile Backcase",
    price: 253,
    freeDelivery: false,
    rating: 4.2,
    reviews: 204,
    image: "images/backcase.jpg",
    qty: 1,
  },
  {
    id: 5,
    name: "Iron Box",
    price: 1300,
    freeDelivery: false,
    rating: 3.8,
    reviews: 498,
    image: "images/ironbox.jpg",
    qty: 1,
  },
  {
    id: 6,
    name: "Extension box",
    price: 200,
    freeDelivery: false,
    rating: 4.1,
    reviews: 180,
    image: "images/extensionbox.jpg",
    qty: 1,
  },
  {
    id: 7,
    name: "Mini Fan",
    price: 1200,
    freeDelivery: true,
    rating: 4.8,
    reviews: 233,
    image: "images/minifan.jpg",
    qty: 1,
  },
  {
    id: 8,
    name: "Electric kettle",
    price: 2500,
    freeDelivery: false,
    rating: 4.4,
    reviews: 500,
    image: "images/electrickettle.jpg",
    qty: 1,
  },
  {
    id: 9,
    name: "Water Purifier",
    price: 13000,
    freeDelivery: true,
    rating: 4.5,
    reviews: 220,
    image: "images/waterpurifer.jpg",
    qty: 1,
  },
  {
    id: 10,
    name: "Vaccum cleaner",
    price: 950,
    freeDelivery: false,
    rating: 4.1,
    reviews: 700,
    image: "images/vaccumcleaner.jpg",
    qty: 1,
  },
  {
    id: 11,
    name: "Laptop Stand",
    price: 2000,
    freeDelivery: true,
    rating: 4.2,
    reviews: 590,
    image: "images/lapstand.jpg",
    qty: 1,
  },
  {
    id: 12,
    name: "Ceiling Fan",
    price: 1950,
    freeDelivery: false,
    rating: 4.1,
    reviews: 398,
    image: "images/ceilingfan.jpg",
    qty: 1,
  },
  {
    id: 13,
    name: "Adidas Shoe",
    price: 2000,
    freeDelivery: false,
    rating: 4.2,
    reviews: 198,
    image: "images/adidasshoe.jpg",
    qty: 1,
  },
  {
    id: 14,
    name: "Hand Bag",
    price: 700,
    freeDelivery: false,
    rating: 4.9,
    reviews: 245,
    image: "images/handbag.jpg",
    qty: 1,
  },
  {
    id: 15,
    name: "Children Bag",
    price: 210,
    freeDelivery: false,
    rating: 4.1,
    reviews: 244,
    image: "images/chidrenbag.jpg",
    qty: 1,
  },
  {
    id: 16,
    name: "Jeans",
    price: 500,
    freeDelivery: false,
    rating: 4.4,
    reviews: 695,
    image: "images/jeans.jpg",
    qty: 1,
  },
  {
    id: 17,
    name: "Trendy T-shirt",
    price: 400,
    freeDelivery: false,
    rating: 4.9,
    reviews: 765,
    image: "images/tshirt.jpg",
    qty: 1,
  },
  {
    id: 18,
    name: "Trouser",
    price: 300,
    freeDelivery: false,
    rating: 3.2,
    reviews: 201,
    image: "images/trousers.jpg",
    qty: 1,
  },
  {
    id: 19,
    name: "Hoodie",
    price: 800,
    freeDelivery: false,
    rating: 4.7,
    reviews: 294,
    image: "images/hoodie.jpg",
    qty: 1,
  },
  {
    id: 20,
    name: "Watch",
    price: 400,
    freeDelivery: false,
    rating: 4.8,
    reviews: 473,
    image: "images/watch.jpg",
    qty: 1,
  },
];

export default Data;
